baseURL = "https://codeandrun.it/"
DefaultContentLanguage = "it"
title = "Code And Run"
theme = "hugo-kiera"
disqusShortname = "alexmufatti"
googleAnalytics = "UA-21196458-5"
enableEmoji = true
pygmentsCodeFences = true
copyright = "Copyright &copy; 2021 - Alex Mufatti"
summaryLength = 20
paginate = 5
enableRobotsTXT = true
rssLimit = 30

[author]
    name = "Alex Mufatti"
    github = "alexmufatti"
    strava = "12353579"
    linkedin = "amufatti"
    twitter = "alexmufatti"
    instagram = "alexmufatti"
    stackoverflow = "606622"
    mastodon = "mastodon.technology/@alexmufatti"
    keybase = "alexmufatti"


[params]
    description = "Personal blog talking about code and running"
    tagline = "Blog of a running developer"
    favicon = "/favicon.ico"
    owner = "Alex Mufatti"
    commentAutoload = true
    mainSections = ["posts", "activities"]
    images = ["/cover.jpg"]


[menu]
    main = [
        { identifier = "home", name = "Home", url = "/", weight=10 },
        { identifier = "about", name = "About", url = "/about", weight=20  },
        { identifier = "conacts", name = "Contacts", url = "/contacts", weight=30  },
        { identifier = "tags", name = "Tags", url = "/tags", weight=40  }

    ]

[permalinks]
  posts = "/:year/:month/:day/:slug/"
  activities = "/:year/:month/:day/:slug/"


[params.twitter]
    creator = "alexmufatti"
    site = "alexmufatti"

[taxonomies]
    tag="tags"
    place="places"
