baseURL = "https://alexmufatti.it/"
DefaultContentLanguage = "it"
title = "Alex Mufatti"
theme = "hugo-kiera"
disqusShortname = "alexmufatti"
googleAnalytics = "UA-21196458-5"
enableEmoji = true
pygmentsCodeFences = true
copyright = "Copyright &copy; 2020 - Alex Mufatti"
summaryLength = 30
paginate = 5
enableRobotsTXT = true

[author]
    name = "Alex Mufatti"           #Author name
    github = "alexmufatti"         #Github username
    strava = "12353579"         #Gitlab username
    linkedin = "amufatti"       #LinkedIn username
    twitter = "alexmufatti"        #Twitter username
    instagram = "alexmufatti"      #Instagram username
    stackoverflow = "606622"  #StackOverflow username
    mastodon = "mastodon.technology/@alexmufatti"  #StackOverflow username
    keybase = "alexmufatti"


[params]
    description = "Personal blog talking about code and running"
    tagline = "Hands on Software"
    favicon = "/favicon.ico"
    owner = "Alex Mufatti"
    commentAutoload = true

[menu]
    main = [
        { identifier = "home", name = "Home", url = "/", weight=10 },
        { identifier = "about", name = "About", url = "/about", weight=20  },
        { identifier = "conacts", name = "Contacts", url = "/contacts", weight=30  },
        { identifier = "tags", name = "Tags", url = "/tags", weight=40  }

    ]

[permalinks]
  posts = "/:year/:month/:day/:slug/"


[params.twitter]
    creator = "alexmufatti"
    site = "alexmufatti"

[taxonomies]
    tag="tags"
